version: '3.3'
services:

  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
      POSTGRES_DB: BWallet

    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - business_wallet
    restart: always

  business-wallet:
    build: .
    ports:
      - "4242:4242"
    networks:
      - business_wallet
    depends_on:
      - postgres

networks:
  business_wallet:
volumes:
  postgres:
